### ISSUE TITLE
Tampermonkey Question

### ISSUE THREAD

**Issue by JacProsser** [cleverkraft/slack-psn-activity#4]
are you able to make a script that will delete friends using tampermonkey?

**Comment by cleverkraft** [comment]
This isn't an issue for this repo, but a question regarding what can be done with Tampermonkey in general.

To answer the question, which is better asked in a Tampermonkey-related venue, anything that can be done in a web browser can be done with Tampermonkey.

You can contact me at alex@cleverkraft.com if you have a question about Tampermonkey development.
